@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 20 18:58:44 -0500 2026
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim fc_bias_tb_behav -key {Behavioral:sim_1:Functional:fc_bias_tb} -tclbatch fc_bias_tb.tcl -view C:/Users/Musta/Documents/GitHub/RISCV_SIM/Base/processor_tb_behav.wcfg -log simulate.log"
call xsim  fc_bias_tb_behav -key {Behavioral:sim_1:Functional:fc_bias_tb} -tclbatch fc_bias_tb.tcl -view C:/Users/Musta/Documents/GitHub/RISCV_SIM/Base/processor_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
